- name: Install Syncthing
  homebrew:
    name: syncthing
    state: present
- name: start syncthing as service
  command: brew services start syncthing
  register: syncthing_service_status
  ignore_errors: yes
# - find:
#     paths: "{{ homebrew_install_path }}"
#     patterns: "*.syncthing.plist"
#     recurse: yes
#   register: syncthing_plist_path
# - debug:
#     msg: "{{ syncthing_plist_path.files[0]['path'] }}"
# - copy:
#     src: "{{ syncthing_plist_path.files[0]['path'] }}"
#     dest: "{{ home }}/Library/LaunchAgents/syncthing.plist"
#     owner: root
#     group: wheel
#     mode: 0644
#   become: true
# - command: "launchctl load {{ home }}/Library/LaunchAgents/syncthing.plist"
#   become: true
#
