---

- name: start syncthing as service
  command: brew services start syncthing
  register: syncthing_service_status
  ignore_errors: yes
  become: false
  
# - find:
#     paths: "{{ homebrew_install_path }}"
#     patterns: "*.syncthing.plist"
#     recurse: yes
#   register: syncthing_plist_path
#   become: false
#
# - debug:
#     msg: "{{ syncthing_plist_path.files[0]['path'] }}"
#
# - copy:
#     src: "{{ syncthing_plist_path.files[0]['path'] }}"
#     dest: "{{ home }}/Library/LaunchAgents/syncthing.plist"
#     owner: root
#     group: wheel
#     mode: 0644
#   when: become_run_commands
#   become: true
#
# - command: "launchctl load {{ home }}/Library/LaunchAgents/syncthing.plist"
#   when: become_run_commands
#   become: true
