bash__powerline_div: "### Theme"
bash__powerline_source: "source {{ home }}/.adrw-bash-powerline.sh"
bash__powerline_url: https://raw.githubusercontent.com/riobard/bash-powerline/master/bash-powerline.sh
bash__powerline_file: .bash-powerline.sh
bash__powerline_adrw_file: .adrw-bash-powerline.sh
