---

- name: save homebrew path to zshrc
  when: shellrc_file.stdout.find('{{ homebrew__path }}') == -1
  shell: echo '{{ homebrew__path }}' >> {{ shellrc.stdout }}
  become: false

- name: turn off homebrew analytics
  when: shellrc_file.stdout.find('{{ homebrew__no_analytics }}') == -1
  shell: echo '{{ homebrew__no_analytics }}' >> {{ shellrc.stdout }}
  become: false

- name: force homebrew no-insecure-redirect
  when: shellrc_file.stdout.find('{{ homebrew__no_insecure_redirect }}') == -1
  shell: echo '{{ homebrew__no_insecure_redirect }}' >> {{ shellrc.stdout }}
  become: false

- name: require-sha
  when: homebrew_cask_require_sha and shellrc_file.stdout.find('{{ homebrew__require_sha }}') == -1
  shell: echo '{{ homebrew__require_sha }}' >> {{ shellrc.stdout }}
  become: false

# https://github.com/geerlingguy/ansible-role-homebrew
# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"
  become: false


# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew: "name={{ item }} state=present"
  with_items: "{{ homebrew_installed_packages }}"
  become: false


- name: Ensure blacklisted homebrew packages are not installed.
  homebrew: "name={{ item }} state=absent"
  with_items: "{{ homebrew_uninstalled_packages }}"
  become: false


- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages
  become: false


# Cask.
- name: Install configured cask applications.
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  with_items: "{{ homebrew_cask_apps }}"
  become: false
  ignore_errors: true

- name: Check for Brewfile.
  stat:
    path: "{{ homebrew_brewfile_dir }}/Brewfile"
  register: homebrew_brewfile
  become: false


- name: Install from Brewfile.
  command: "brew bundle chdir={{ homebrew_brewfile_dir }}"
  when: homebrew_brewfile.stat.exists and homebrew_use_brewfile
  become: false
