- name: Clone Maximum Awesome https://github.com/square/maximum-awesome
  git:
    update: yes
    version: master
    repo: https://github.com/square/maximum-awesome.git
    dest: "{{ home }}/.maximum-awesome"
    force: yes
- name: Install Maximum Awesome
  command:
    chdir: "{{ home }}/.maximum-awesome"
    cmd: rake
