- name: Clone Maximum Awesome https://github.com/square/maximum-awesome
  git:
    update: yes
    version: master
    repo: https://github.com/square/maximum-awesome.git
    dest: "{{ home }}/.maximum-awesome"
    force: yes
# Don't install since it now requires [ENTER]
# - name: Install Maximum Awesome
#   command:
#     chdir: "{{ home }}/.maximum-awesome"
#     cmd: rake
- file:
    src: "{{ roles_dir }}/square-maximum-awesome/files/.vimrc.local"
    dest: "{{ home }}/.vimrc.local"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- file:
    src: "{{ roles_dir }}/square-maximum-awesome/files/.vimrc.bundles.local"
    dest: "{{ home }}/.vimrc.bundles.local"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
