---

- unarchive:
    src: "{{ roles_dir }}/automator-workflows/files/CombinePDF20.zip"
    dest: "{{ home }}/Library/Services/"
    force: yes
  

- file:
    path: "{{ home }}/Library/Services/__MACOSX"
    state: absent
    force: yes
  
