---
# osx.sh - https://github.com/donnemartin/dev-setup/blob/master/osx.sh
# - osx_defaults:
#     domain:
#     key:
#     type:
#     value:
#     state:

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Disable transparency in the menu bar and elsewhere on Yosemite
# defaults write com.apple.universalaccess reduceTransparency -bool true

# Menu bar: hide the Time Machine, Volume, and User icons
# for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
#     defaults write "${domain}" dontAutoLoad -array \
#         "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
#         "/System/Library/CoreServices/Menu Extras/Volume.menu" \
#         "/System/Library/CoreServices/Menu Extras/User.menu"
# done
# defaults write com.apple.systemuiserver menuExtras -array \
#     "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
#     "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
#     "/System/Library/CoreServices/Menu Extras/Battery.menu" \
#     "/System/Library/CoreServices/Menu Extras/Clock.menu"

# Set highlight color to green
#defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"

# Set sidebar icon size to medium
# defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Always show scrollbars
#defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

# Disable smooth scrolling
# (Uncomment if you’re on an older Mac that messes up the animation)
#defaults write NSGlobalDomain NSScrollAnimationEnabled -bool false

- name: increase Cocoa app resize speed
  osx_defaults:
    domain: NSGlobalDomain
    key: NSWindowResizeTime
    type: float
    value: 0.001
    state: present

- name: expand save panel
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
    state: present
- osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true
    state: present

- name: expand print panel
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
    state: present
- osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true
    state: present

- name: save to disk (not iCloud)
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: quit printer app once print job complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

- name: check software updates daily
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
    state: present

# - name: set wallpaper
#   file:
#     path: "{{ home }}/Library/Application Support/Dock/desktoppicture.db"
#     state: absent
#   become: true
#
# - file:
#     path: /System/Library/CoreServices/DefaultDesktop.jpg
#     state: absent
#   become: true
#
# - file:
#     src: "{{ desktop_picture_path }}"
#     dest: /System/Library/CoreServices/DefaultDesktop.jpg
#     state: link
#     force: yes
#   become: true

###############################################################################
# SSD-specific tweaks                                                         #
# You might want to disable these if you are not running an SSD               #
###############################################################################

# # Disable local Time Machine snapshots
# sudo tmutil disablelocal
#
# # Disable hibernation (speeds up entering sleep mode)
# sudo pmset -a hibernatemode 0
#
# # Remove the sleep image file to save disk space
# sudo rm -f /private/var/vm/sleepimage
# # Create a zero-byte file instead…
# sudo touch /private/var/vm/sleepimage
# # …and make sure it can’t be rewritten
# sudo chflags uchg /private/var/vm/sleepimage


- name: disable sudden motion sensor, not useful for SSDs
  shell: pmset -a sms 0
  become: true






















# a
