---

# package manager https://packagecontrol.io/installation

- name: Install MacDown
  homebrew_cask:
    name: macdown
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  become: false
  ignore_errors: true

- name: Ensure custom CSS directory present
  file:
    path: "{{ home }}/{{ macdown_styles_dest }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    recurse: yes
  when: become_skip is not defined or not become_skip
  become: true

- name: Link over custom CSS
  file:
    src: "{{ roles_dir }}/{{ macdown_role_file }}/GitHubAP.css"
    dest: "{{ home }}/{{ macdown_styles_dest }}/GitHubAP.css"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false
  ignore_errors: true

- name: Link over custom CSS
  file:
    src: "{{ roles_dir }}/{{ macdown_role_file }}/LatexAP.css"
    dest: "{{ home }}/{{ macdown_styles_dest }}/LatexAP.css"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false
  ignore_errors: true

- name: Link over custom CSS
  file:
    src: "{{ roles_dir }}/{{ macdown_role_file }}/PrintAP.css"
    dest: "{{ home }}/{{ macdown_styles_dest }}/PrintAP.css"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false
  ignore_errors: true