---

# package manager https://packagecontrol.io/installation

- name: Install MacDown
  homebrew_cask:
    name: macdown
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  become: false
  ignore_errors: true

- name: Link over custom CSS
  file:
    src: "{{ roles_dir }}/{{ macdown_role_file }}/GitHubAP.css"
    dest: "{{ home }}/{{ macdown_styles_dest }}/GitHubAP.css"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false