# package manager https://packagecontrol.io/installation

- name: Install MacDown
  homebrew_cask:
    name: macdown
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
- name: ensure MacDown Styles exists
  stat:
    path: "{{ home }}/{{ macdown_styles_dest }}"
  register: mds
- name: Ensure custom CSS directory present
  file:
    path: "{{ home }}/{{ macdown_styles_dest }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    recurse: yes
  when:
    - not mds.stat.exists
  become: true
- name: Link over custom CSS
  file:
    src: "{{ roles_dir }}/{{ macdown_role_file }}/{{ item }}"
    dest: "{{ home }}/{{ macdown_styles_dest }}/{{ item }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  with_items: "{{ macdown_styles }}"
