---
galaxy_info:
  author: Andrew Paradi
  company: 
  license: MIT
  min_ansible_version: 2.0
  platforms:
   - name: Darwin
     versions:
      - trusty
      - vivid
      - xenial
dependencies: []
