---

- file:
    src: "{{ roles_dir }}/adrw-shell/files/{{ adrw_shell__aliases }}"
    dest: "{{ home }}/{{ adrw_shell__aliases }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- file:
    src: "{{ roles_dir }}/adrw-shell/files/{{ adrw_shell__functions }}"
    dest: "{{ home }}/{{ adrw_shell__functions }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- file:
    path: "{{ home }}/.bashrc"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false

- file:
    path: "{{ home }}/.zshrc"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false

- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} ADRW Shell"
    content: "{{ adrw_shell__source }}"
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} ADRW Shell"
    content: "{{ adrw_shell__source }}"
  become: false
  ignore_errors: true
