- name: Add pyenv to .bashrc
  blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ pyenv__div }}"
    content: "{{ pyenv__content }}"
    create: true
- name: Add pyenv to .zshrc
  blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ pyenv__div }}"
    content: "{{ pyenv__content }}"
    create: true
