- name: Install Bash Powerline Theme
  get_url:
    url: "{{ bash__powerline_url }}"
    dest: "{{ roles_dir }}/bash/files/{{ bash__powerline_file }}"
    mode: 0644
    force: yes
    backup: yes
- file:
    src: "{{ roles_dir }}/bash/files/{{ bash__powerline_adrw_file }}"
    dest: "{{ home }}/{{ bash__powerline_adrw_file }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ bash__powerline_div }}"
    content: "{{ bash__powerline_source }}"
    create: true
- lineinfile:
    dest: "{{ home }}/.bash_profile"
    state: present
    line: "source {{ home }}/.bashrc"
    create: true
