---

- file:
    src: "{{ roles_dir }}/functions/files/{{ functions__filename }}"
    dest: "{{ home }}/{{ functions__filename }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- name: save functions path to zshrc
  lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ functions__source }}"
  become: false

- file:
    path: "{{ home }}/.bashrc"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false

- name: save functions path to bashrc
  lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ functions__source }}"
  become: false
