---

square_init_div: "### Square Andrew Paradi"

square_aliases_filename: .ap-square-aliases
square_aliases_source: 'source {{home}}.ap-square-aliases'

square_functions_filename: .ap-square-functions
square_functions_source: 'source {{home}}.ap-square-functions'