---

square_init_div: "### Square adrw"

square_aliases_filename: .adrw-square-aliases
square_aliases_source: 'source {{ home }}/.adrw-square-aliases'

square_functions_filename: .adrw-square-functions
square_functions_source: 'source {{ home }}/.adrw-square-functions'