---

- file:
    path: "{{ home }}.ssh/"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0700
  become: false


- file:
    src: "{{ roles_dir }}/ssh/files/config"
    dest: "{{ home }}.ssh/config"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0600
    force: yes
  become: false

- name: "generate id_rsa key to {{ id_rsa }}"
  user:
    name: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ id_rsa }}"
    ssh_key_passphrase: "{{ ssh_passphrase }}"
  become: false

- name: Add id_rsa to ssh agent
  shell: "ssh-add -K {{ id_rsa }}"
  become: false
