---

- name: "generate id_rsa key to {{ id_rsa }}"
  user:
    name: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ id_rsa }}"
    ssh_key_passphrase: "{{ ssh_passphrase }}"
  
