homebrew_packages:
  - cheat
  - exiftool # photo manipulation script
  - figlet
  # - gnupg2  # requires java...
  - hub
  - htop
  - jhead # photo manipulation script
  - node
  - nvm
  - openssl
  - pngquant
  - python
  - python3
  - shellcheck
  - tldr
  - travis
  - tree
  - wget
  - yarn
# Packages included in other roles
# - antibody
# - dockutil
# - fasd
# - privoxy
# - syncthing
# - tmux
