homebrew_packages:
  - act
  - bat
  - certbot
  - cheat
  - coreutils
  - exiftool # photo manipulation script
  - figlet
  - git-quick-stats
  - gh # github
  # - gnupg2  # requires java...
  - hub
  - htop
  - jhead # photo manipulation script
  - jo
  - jq
  - mysql-client
  - neofetch
  - node
  - openssl
  - pngquant
  - pyenv
  - python
  - python3
  - ripgrep
  - shellcheck
  - speedtest-cli
  - tldr
  - travis
  - tree
  - wget
  - yarn
# Packages included in other roles
# - antibody
# - dockutil
# - fasd
# - nvm
# - privoxy
# - syncthing
# - tmux
