homebrew_apps_development:
  # - anaconda  # python ML libraries
  # - coda
  - dash
  - docker
  - insomnia
  - intellij-idea
  # - java11 # not current enough for work purposes
  - ngrok
  # - sqlpro-for-sqlite
  - visual-studio-code
# Packages included in other roles
# - atom
# - iterm2
# - macdown
# - sublime-text

