homebrew_packages:
  - cheat
  - exiftool  # photo manipulation script
  - figlet
  # - gnupg2  # requires java...
  - htop
  - jhead     # photo manipulation script
  - node
  - openssl
  - pngquant
  - python
  - python3
  - shellcheck
  - tldr
  - travis
  - tree
  - wget
  - yarn

# Packages included in other roles
# - antibody
# - dockutil
# - fasd
# - privoxy
# - syncthing
# - tmux
