- name: Include npm vars files
  include_vars:
    dir: ../vars/
    extensions:
      - yml
- name: install global npm packages
  npm: "name={{ item }} global=yes"
  with_items: "{{ npm_packages|flatten(levels=1) }}"
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ npx__div }}"
    content: "{{ npx__init }}"
    create: true
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ npx__div }}"
    content: "{{ npx__init }}"
    create: true
