---

dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar

dockitems_to_persist:
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 1
  - name: iTerm2
    path: /Applications/iTerm2.app
    pos: 6
  - name: Atom
    path: /Applications/Atom.app
    pos: 7
