---

dockitems_to_remove:
  - Siri
  - Launchpad
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - FaceTime
  - iBooks
  - App Store

dockitems_to_persist:
  # - name: Messages
  #   path: "/Applications/Messages.app"
  #   pos: 2
