---

dockitems_to_remove:
  - Siri
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences

dockitems_to_persist:
  # - name: Messages
  #   path: "/Applications/Messages.app"
  #   pos: 2
