- homebrew_installed_packages:
    - antibody
    - cheat
    # - dockutil  # separate role
    - exiftool  # photo manipulation script
    # - fasd    # separate role
    - figlet
    # - gnupg2  # requires java...
    - htop
    - jhead     # photo manipulation script
    # - mas
    - node
    - openssl
    - pngquant
    # - privoxy # separate role
    # - python    # broken in Command Line Tools 10.14+ https://github.com/Homebrew/homebrew-core/issues/31679
    # - python3   # broken in Command Line Tools 10.14+ https://github.com/Homebrew/homebrew-core/issues/31679
    - shellcheck
    # - syncthing # separate role
    - tldr
    - tmux
    - travis
    - tree
    - wget
    - yarn