---

- lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ square_init_div }}"
  become: false

- lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ square_init_div }}"
  become: false

- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### Square Franklin Aliases"
    content: "if [[ -f \"$SQUARE_HOME/java/franklin/bash_aliases\" ]]; then
      \n\tsource $SQUARE_HOME/java/franklin/bash_aliases
      \nfi"
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### Square Franklin Aliases"
    content: "if [[ -f \"$SQUARE_HOME/java/franklin/bash_aliases\" ]]; then
      \n\tsource $SQUARE_HOME/java/franklin/bash_aliases
      \nfi"
  become: false
  ignore_errors: true

- name: AP-Square-Aliases
  file:
    src: "{{ roles_dir }}/square/files/{{ square_aliases_filename }}"
    dest: "{{ home }}/{{ square_aliases_filename }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ square_aliases_source }}"
  become: false

- lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ square_aliases_source }}"
  become: false

- name: AP-Square-Functions
  file:
    src: "{{ roles_dir }}/square/files/{{ square_functions_filename }}"
    dest: "{{ home }}/{{ square_functions_filename }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ square_functions_source }}"
  become: false

- lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ square_functions_source }}"
  become: false
