---
  
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} Square Franklin Aliases"
    content: "{{ square__franklin_aliases }}"
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} Square Franklin Aliases"
    content: "{{ square__franklin_aliases }}"
  become: false
  ignore_errors: true

- name: ADRW Square Aliases
  file:
    src: "{{ roles_dir }}/square/files/{{ square__aliases }}"
    dest: "{{ home }}/{{ square__aliases }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- name: ADRW Square Functions
  file:
    src: "{{ roles_dir }}/square/files/{{ square__functions }}"
    dest: "{{ home }}/{{ square__functions }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} ADRW Shell Square"
    content: "{{ square__adrw_shell_source }}"
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} ADRW Shell Square"
    content: "{{ square__adrw_shell_source }}"
  become: false
  ignore_errors: true