- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__franklin_div }}"
    content: "{{ square__franklin_aliases }}"
    create: true
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__franklin_div }}"
    content: "{{ square__franklin_aliases }}"
    create: true
- file:
    src: "{{ roles_dir }}/square/files/{{ square__aliases }}"
    dest: "{{ home }}/{{ square__aliases }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- file:
    src: "{{ roles_dir }}/square/files/{{ square__functions }}"
    dest: "{{ home }}/{{ square__functions }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__div }}"
    content: "{{ square__adrw_shell_source }}"
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__div }}"
    content: "{{ square__adrw_shell_source }}"
- name: "Polyrepo Env Variable"
  blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__polyrepo_div }}"
    content: "{{ square__polyrepo }}"
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__polyrepo_div }}"
    content: "{{ square__polyrepo }}"
- name: Configure square tap
  homebrew_tap:
    name: "{{ square__homebrew_tap_name}}"
    url: "{{ square__homebrew_tap_url }}"
- name: Install Square specific brew packages
  command: "brew install {{ item }}"
  loop: "{{ homebrew_installed_packages|flatten(levels=1) }}"
- name: Ensure configured homebrew packages are installed from homebrew_packages.
  command: "brew install {{ item }}"
  loop: "{{ square__homebrew_packages|flatten(levels=1) }}"
