- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__franklin_div }}"
    content: "{{ square__franklin_aliases }}"
    create: true
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__franklin_div }}"
    content: "{{ square__franklin_aliases }}"
    create: true
- file:
    src: "{{ roles_dir }}/square/files/{{ square__aliases }}"
    dest: "{{ home }}/{{ square__aliases }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- file:
    src: "{{ roles_dir }}/square/files/{{ square__functions }}"
    dest: "{{ home }}/{{ square__functions }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__div }}"
    content: "{{ square__adrw_shell_source }}"
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__div }}"
    content: "{{ square__adrw_shell_source }}"
- name: "Polyrepo Env Variable"
  blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} {{ square__polyrepo_div }}"
    content: "{{ square__polyrepo }}"
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ square__polyrepo_div }}"
    content: "{{ square__polyrepo }}"
- name: Configure Square tap
  homebrew_tap:
    name: "{{ square__homebrew_tap_name}}"
    url: "{{ square__homebrew_tap_url }}"
- name: Install Square specific brew packages
  command: "brew install {{ item }}"
  loop: "{{ square__homebrew_packages|flatten(levels=1) }}"
- name: Install Babushka
  shell: sh -c "`curl https://babushka.me/up`" </dev/null
  become: true
- name: Create code directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items: "{{ square__code_directories }}"
- name: Clone code repos
  shell: git clone {{ item.url }}
  args:
    chdir: "{{ home }}/Development"
    creates: "{{ home }}/Development/{{ item.name }}"
  with_items: "{{ square__development_repositories }}"
- name: Add Square/topsoil deps to Babushka (go/notopsoil)
  file:
    src: "{{ square__topsoil_babushka_deps }}"
    dest: "{{ square__babushka_deps }}"
    state: link
  become: true
- name: Install python requirements for MkDocs documentation
  pip:
    name: "{{ square__pip_packages }}"
    extra_args: "--user"
