---

# - name: install dnscrypt-proxy
#   homebrew:
#     name: dnscrypt-proxy
#   become: false
# - name: start dnscrypt-proxy as service
#   command: brew services start dnscrypt-proxy
#   become: true
