---

- file:
    src: "{{ roles_dir }}/aliases/files/{{ aliases__filename }}"
    dest: "{{ home }}/{{ aliases__filename }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- name: add other section to zshrc
  lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ aliases__div }}"
  become: false

- name: save aliases path to zshrc
  lineinfile:
    dest: "{{ home }}/.zshrc"
    state: present
    line: "{{ aliases__source }}"
  become: false

- file:
    path: "{{ home }}/.bashrc"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
  become: false

- name: add other section to bashrc
  lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ aliases__div }}"
  become: false

- name: save aliases path to bashrc
  lineinfile:
    dest: "{{ home }}/.bashrc"
    state: present
    line: "{{ aliases__source }}"
  become: false
