- name: Include vscode vars files
  include_vars:
    dir: ../vars/
    extensions:
      - yml
- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
- name: Ensure configured vscode packages are installed.
  shell: "code install {{ item }}"
  loop: "{{ vscode_packages|flatten(levels=1) }}"
