---

- file:
    src: "{{ roles_dir }}/git/files/.gitconfig"
    dest: "{{ home }}/.gitconfig"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  
