---

- name: Install Anaconda
  homebrew_cask:
    name: anaconda
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} Anaconda / Jupyter ML Notebooks"
    content: "{{ anaconda__path }}"
    create: true
  become: false
  ignore_errors: true

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} Anaconda / Jupyter ML Notebooks"
    content: "{{ anaconda__path }}"
    create: true
  become: false
  ignore_errors: true
