---

  - file:
      src: "{{ roles_dir }}/vim/files/.vimrc"
      dest: "{{ home }}/.vimrc"
      state: link
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
      mode: 0644
      force: yes
    become: false
