- name: Clone Awesome Ultimate vimrc https://github.com/amix/vimrc
  git:
    update: yes
    version: master
    repo: https://github.com/amix/vimrc.git
    dest: "{{ home }}/.vim_runtime"
- name: Install Awesome Ultimate vimrc https://github.com/amix/vimrc
  command: sh ~/.vim_runtime/install_awesome_vimrc.sh
- file:
    src: "{{ roles_dir }}/vim/files/.vimrc"
    dest: "{{ home }}/.vimrc"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
- blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "### {mark} ADRW Editor"
    content: "{{ vim__editor }}"
    create: true
- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} ADRW Editor"
    content: "{{ vim__editor }}"
    create: true
