---

  - file:
      src: "{{ roles_dir }}/vim/files/.vimrc"
      dest: "{{ home }}/.vimrc"
      state: link
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
      mode: 0644
      force: yes
    become: false

  - blockinfile:
      dest: "{{ home }}/.bashrc"
      marker: "### {mark} ADRW Editor"
      content: "{{ vim__editor }}"
    become: false
    ignore_errors: true

  - blockinfile:
      dest: "{{ home }}/.zshrc"
      marker: "### {mark} ADRW Editor"
      content: "{{ vim__editor }}"
    become: false
    ignore_errors: true
