---

- name: Register Antibody
  shell: echo 'source <(antibody init)'
  register: antibody_source
  become: false

- file:
    src: "{{ roles_dir }}/{{ antibody__rolename }}/files/{{ antibody__plugins_list }}"
    dest: "{{ home }}/{{ antibody__plugins_list }}"
    state: link
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0644
    force: yes
  become: false

- name: Antibody Bundle
  shell: antibody bundle < "{{ home }}/{{ antibody__plugins_list }}" > "{{ home }}/{{ antibody__plugins_zsh }}"
  become: false

- blockinfile:
    dest: "{{ home }}/.zshrc"
    marker: "### {mark} {{ antibody__div }}"
    content: "{{ antibody_source.stdout }}
      \nsource {{ home }}/{{ antibody__plugins_zsh }}
      \n{{ zsh__default_user }}"
    create: true
  become: false
  ignore_errors: true
  
