---

- homebrew:
    name: dockutil
    state: present
  become: false

- name: wipe
  shell: dockutil --remove "{{ item }}"
  with_items: "{{dockitems_to_remove}}"
  become: false

- name: if item exists, add to dock
  shell: dockutil --find "{{ item.name }}" || dockutil --add "{{ item.path }}"
  with_items: "{{dockitems_to_persist}}"
  become: false

- name: fix order
  shell: dockutil --move "{{ item.name }}" --position {{ item.pos }}
  with_items: "{{dockitems_to_persist}}"
  become: false
