- homebrew:
    name: dockutil
    state: present
- name: wipe
  shell: dockutil --remove "{{ item }}"
  with_items: "{{dockitems_to_remove}}"
- name: wipe defaults
  shell: dockutil --remove "{{ item }}"
  with_items: "{{default_dockitems_to_remove}}"
- name: if item exists, add to dock
  shell: dockutil --find "{{ item.name }}" || dockutil --add "{{ item.path }}"
  with_items: "{{dockitems_to_persist}}"
- name: fix order
  shell: dockutil --move "{{ item.name }}" --position {{ item.pos }}
  with_items: "{{dockitems_to_persist}}"
