sublime_packages:
  - dest: "Solarized"
    repo: "https://github.com/braver/Solarized.git"
    version: "master"
  - dest: "SideBarEnhancements"
    repo: "https://github.com/titoBouzout/SideBarEnhancements"
    version: "st3"
  - dest: "GitGutter"
    repo: "https://github.com/jisaacks/GitGutter.git"
    version: "master"
  - dest: "BracketHighlighter"
    repo: "https://github.com/facelessuser/BracketHighlighter.git"
    version: "master"
  - dest: "ApplySyntax"
    repo: "https://github.com/facelessuser/ApplySyntax.git"
    version: "master"
  - dest: "SublimeAllAutocomplete"
    repo: "https://github.com/alienhard/SublimeAllAutocomplete"
    version: "master"
  - dest: "Ansible"
    repo: "https://github.com/clifford-github/sublime-ansible.git"
    version: "master"