---

# customizations, profile, default font size

# Install the Solarized Dark theme for iTerm
# open "${HOME}/init/Solarized Dark.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
# defaults write com.googlecode.iterm2 PromptOnQuit -bool false



# powerlevel9k, solarized theme https://gist.github.com/kevin-smets/8568070
# also need to download meslo font
