---

- name: Install MacDown
  homebrew_cask:
    name: iterm2
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  become: false
  ignore_errors: true

- osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false
    state: present

- name: install theme
  shell: open {{ roles_dir }}/iterm2/files/Solarized-High-Contrast-Dark.itermcolors
  become: false

# customizations, profile, default font size

# Install the Solarized Dark theme for iTerm
# open "${HOME}/init/Solarized Dark.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
# defaults write com.googlecode.iterm2 PromptOnQuit -bool false

# powerlevel9k, solarized theme https://gist.github.com/kevin-smets/8568070
