# Use from main repo: ./bootstrap.sh -u {username} -p mac_clean

---

- hosts: macbox
  connection: local
  roles:
    - spoof-mac
    - etchosts
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - aliases
    - functions
    - tmux
    - vim
    - privoxy
    - automator-workflows
    - dockutil
    - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    roles_dir: "{{ home }}/.files/ansible/roles"

    homebrew_cask_require_sha: false
    homebrew_cask_appdir: /Applications
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - getantibody/homebrew-antibody
    homebrew_installed_packages:
      - antibody
      - cheat
      # - dockutil  # separate role
      - exiftool  # photo manipulation script
      - figlet
      - htop
      - jhead     # photo manipulation script
      - node
      - openssl
      # - privoxy # separate role
      - python
      - python3
      - tldr
      - tmux
      - tree
      - wget
      - yarn
    homebrew_cask_apps:
      - 1password
      - alfred
      - appcleaner
      - bartender
      - caffeine
      - dropbox
      - firefox-developer-edition
      - google-chrome
      - ipartition
      # - iterm2    # separate role
      - karabiner-elements  # requires password
      - ngrok
      # - macdown     # separate role
      - microsoft-office  # requires password
      - signal
      - spectacle
      - spotify
      - teamviewer
      - the-unarchiver
      - torbrowser
      - transmission
      - visual-studio-code
      - vlc
      - whatsapp
    # fonts
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome

    dockitems_to_persist:
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 2
      - name: Signal
        path: "/Applications/Signal.app"
        pos: 3
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 4
      - name: Firefox Developer Edition
        path: "/Applications/Firefox Developer Edition.app"
        pos: 5
      - name: Safari
        path: "/Applications/Safari.app"
        pos: 6
      - name: Preview
        path: /Applications/Preview.app
        pos: 7
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 8

    dockitems_to_remove: