---

- hosts: macbox
  connection: local
  roles:
    - square
    # - spoof-mac
    # - etchosts
    # - oh-my-zsh
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - aliases
    - functions
    - git
    - tmux
    - vim
    - atom
    - sublime-text
    - macdown
    - ssh #id_rsa key generation
    # - privoxy
    # - syncthing
    - automator-workflows
    # - anaconda
    # - dnscrypt
    # - gpg
    # - mas
    - dockutil
    - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: false

    homebrew_cask_require_sha: false
    homebrew_cask_appdir: /Applications
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-versions
      - homebrew/cask-fonts
      - getantibody/homebrew-antibody
    homebrew_installed_packages:
      - antibody
      - cheat
      # - dockutil  # separate role
      - exiftool  # photo manipulation script
      # - fasd    # separate role
      - figlet
      # - gnupg2  # requires java...
      - htop
      - jhead     # photo manipulation script
      # - mas
      - node
      - openssl
      - pngquant
      # - privoxy # separate role
      - python
      - python3
      # - syncthing
      - tldr
      - tmux
      - tree
      - wget
      - yarn
    homebrew_cask_apps:
      - 1password
      # - adobe-digital-editions
      - alfred
      # - anaconda  # python ML libraries
      - appcleaner
      # - atom      # separate role
      # - autodmg
      # - backblaze
      # - backblaze-downloader
      - bartender
      # - calibre
      - caffeine
      # - createuserpkg
      # - coda
      - dash
      - docker
      - dropbox
      # - eloston-chromium
      # - firefox
      - firefox-developer-edition
      # - firefox-esr
      # - gmvault
      - google-chrome
      # - google-chrome-canary
      # - gpgtools-beta
      # - handbrake
      # - handbrakebatch
      - imagealpha
      # - insomnia
      - intellij-idea
      # - intellij-idea-ce
      # - ipartition
      # - iterm2    # separate role
      - karabiner-elements  # requires password
      # - keybase
      # - kdiff3
      - ngrok
      # - macdown     # separate role
      # - mediahuman-audio-converter
      # - mediahuman-youtube-downloader
      # - microsoft-office  # requires password
      # - musicbrainz-picard
      # - onedrive      # requires password
      # - protonmail-bridge
      - quitter
      # - signal
      # - skype
      - slack
      - spectacle
      - spotify
      # - sqlpro-for-sqlite
      # - standard-notes
      # - sublime-text # separate role
      # - synology-assistant
      - the-unarchiver
      - torbrowser
      # - transmission
      - utc-menu-clock
      # - virtualbox    # requires password
      # - viscosity
      - visual-studio-code
      # - vlc
      # - whatsapp
    # fonts
      - font-arvo     # for OAKWEAR & CO.
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome

    sublime_packages:
      - dest: "Solarized"
        repo: "https://github.com/braver/Solarized.git"
        version: "master"
      - dest: "SideBarEnhancements"
        repo: "https://github.com/titoBouzout/SideBarEnhancements"
        version: "st3"
      - dest: "GitGutter"
        repo: "https://github.com/jisaacks/GitGutter.git"
        version: "master"
      - dest: "BracketHighlighter"
        repo: "https://github.com/facelessuser/BracketHighlighter.git"
        version: "master"
      - dest: "ApplySyntax"
        repo: "https://github.com/facelessuser/ApplySyntax.git"
        version: "master"
      - dest: "SublimeAllAutocomplete"
        repo: "https://github.com/alienhard/SublimeAllAutocomplete"
        version: "master"
      - dest: "Ansible"
        repo: "https://github.com/clifford-github/sublime-ansible.git"
        version: "master"
      - dest: "Kotlin"
        repo: "https://github.com/vkostyukov/kotlin-sublime-package.git"
        version: "master"

    sublime_text_color_scheme: "Packages/Solarized/Solarized (dark).tmTheme"
    # sublime_text_theme: "Soda Dark 3.sublime-theme"

    atom_packages:
      - busy-signal
      - language-babel
      - language-docker
      - language-gdb
      - language-javascript-jsx
      - language-markdown
      - language-scala
      - linter
      - linter-eslint
      - linter-ui-default
      - intentions
      - markdown-preview-plus
      - markdown-scroll-sync
      - markdown-writer
      - multi-cursor
      - remote-sync

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      - { id: 824183456, name: "Affinity Photo" }
      - { id: 824171161, name: "Affinity Designer" }
      - { id: 979047768, name: "Browserism for Chrome" }
      - { id: 420212497, name: "Byword (2.8)" }
      - { id: 975937182, name: "Fantastical 2 - Calendar and Reminders" }
      - { id: 424389933, name: "Final Cut Pro" }
      - { id: 402989379, name: "iStudiez Pro - Homework, Schedule, Grades" }
      - { id: 409201541, name: "Pages" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 1
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 2
      - name: Firefox Developer Edition
        path: "/Applications/Firefox Developer Edition.app"
        pos: 3
      - name: MacDown
        path: /Applications/MacDown.app
        pos: 4
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app
        pos: 5
      - name: IntelliJ IDEA
        path: /Applications/IntelliJ IDEA.app
        pos: 6
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 7
      - name: Preview
        path: /Applications/Preview.app
        pos: 8
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 9

    dockitems_to_remove: