- import_playbook: mac_dev.yml

- hosts: macbox
  connection: local
  roles:
    - square
    - square-go
    - homebrew
    - dockutil
    - macos
  become_method: sudo
  ignore_errors: true
  vars:
    install_homebrew_apps_password: "{{ become }}"
    install_homebrew_fonts: true
    install_ssh: true # set to false to rely on Square ssh config and keys
    dockitems_to_persist:

    dockitems_to_remove:
