---

- hosts: macbox
  connection: local
  roles:
    - spoof-mac
    - etchosts
    # - oh-my-zsh
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - aliases
    - functions
    # - git
    - tmux
    - vim
    # - ssh #id_rsa key generation
    - privoxy
    # - syncthing
    - automator-workflows
    # - anaconda
    # - dnscrypt
    # - gpg
    - dockutil
    - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    # user_name: me # require it as input
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_cask_appdir: /Applications
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - getantibody/homebrew-antibody
    homebrew_installed_packages:
      - antibody
      - cheat
      # - dockutil  # separate role
      - exiftool  # photo manipulation script
      # - fasd    # separate role
      - figlet
      # - gnupg2  # requires java...
      - htop
      - jhead     # photo manipulation script
      - node
      - openssl
      # - privoxy # separate role
      - python
      - python3
      # - syncthing
      - tldr
      - tmux
      - tree
      - wget
      - yarn
    homebrew_cask_apps:
    # fonts
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome

    dockitems_to_persist:
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 2
      - name: Signal
        path: "/Applications/Signal.app"
        pos: 3
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 4
      - name: Firefox Developer Edition
        path: "/Applications/Firefox Developer Edition.app"
        pos: 5
      - name: Safari
        path: "/Applications/Safari.app"
        pos: 6
      - name: Preview
        path: /Applications/Preview.app
        pos: 7
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 8

    dockitems_to_remove: