- hosts: macbox
  connection: local
  roles:
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - adrw-shell
    - git
    - tmux
    - vim
    - ssh
    - travis
    - go
    - iterm2
    # - oh-my-zsh
    # - mas
  become_method: sudo
  ignore_errors: true
  vars:
    install_homebrew_packages: true
    install_homebrew_fonts: true
