---

- hosts: macbox
  connection: local
  roles:
    - adrw-shell
    - anaconda
    - atom
    - automator-workflows
    - bash
    - dnscrypt
    - dockutil
    - etchosts
    - fasd
    - git
    - gpg
    - iterm2
    - macdown
    - macos
    - mas
    - oh-my-zsh
    - privoxy
    - spoof-mac
    - square
    - ssh
    - sublime-text
    - syncthing
    - tmux
    - vim
    - zmv
    - zsh
    - zsh-antibody

  become_method: sudo
  ignore_errors: true

  vars:
    