- hosts: macbox
  connection: local
  roles:
    - spoof-mac
    - etchosts
    - privoxy
    # - syncthing
    # - dnscrypt
    # - gpg
    - macos

  become_method: sudo
  ignore_errors: true
  vars:
