- hosts: macbox
  connection: local
  roles:
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - fzf
    - adrw-shell
    - git
    - ssh
    - nvm
    - npm
    - pyenv
    # - fisher # need to figure out how to run the install
    - starship
    - square-maximum-awesome
    - tmux-themepack
    # Replaced by Square Maximum Awesome
    # TODO bring back uptime tmux widget
    # - tmux
    # - vim
    # - iterm2
  become_method: sudo
  ignore_errors: true
  vars:
    install_homebrew_packages: true
    install_homebrew_fonts: true
    install_ssh: true
