---

- hosts: macbox
  connection: local
  roles:
    - spoof-mac
    - etchosts
    - privoxy
    - zsh-antibody

  become: true
  become_method: sudo

  vars:
    become_skip: false
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"