---

- hosts: macbox
  connection: local
  roles:
    - etchosts
    - homebrew
    - privoxy
  become: yes
  become_method: sudo

  vars:
    user_name: me
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"

    filevault_auto_evict: true
    cache_libraries: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/cask
      - caskroom/versions
      - caskroom/fonts
    homebrew_installed_packages:
      - privoxy
    homebrew_cask_apps:
    # fonts
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome
