---

- hosts: macbox
  connection: local
  roles:
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - adrw-shell
    - git
    - tmux
    - vim
    - ssh
    - iterm2
    # - oh-my-zsh
    # - mas
    - { role: homebrew, when: not fast_mode }

  become_method: sudo

  vars:
    install_homebrew_packages: true
    install_homebrew_fonts: true