---

- hosts: macbox
  connection: local
  roles:
    # - calibre # only needs to be run once
    - etchosts
    # - oh-my-zsh
    - homebrew
    - antibody-zsh
    - bash
    - zsh
    - aliases
    - functions
    - git
    - tmux
    - vim
    - atom
    - ssh #id_rsa key generation
    - privoxy
    - syncthing
    - automator-workflows
    - anaconda
    # - dnscrypt
    # - gpg
    # - mas
    - dockutil
    - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    user_name: me
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/versions
      - caskroom/fonts
      - getantibody/homebrew-antibody
    homebrew_installed_packages:
      - antibody
      - cheat
      - dockutil
      # - gnupg2 # requires java...
      - htop
      - mas
      - node
      - openssl
      - privoxy
      - python
      - python3
      - syncthing
      - tldr
      - tmux
      - wget
      - yarn
    homebrew_cask_apps:
      - 1password
    #   - adobe-digital-editions
      - alfred
      - anaconda # python ML libraries
      - appcleaner
      - atom
      # - autodmg
      # - backblaze
      # - backblaze-downloader
      - bartender
      # - calibre
      - coda
      - dash
      - docker
      - dropbox
      - eloston-chromium
      - firefox
      # - flux
      - gmvault
      - google-chrome
      - google-chrome-canary
      - gpgtools-beta
      # - handbrake
      # - handbrakebatch
      # - imagealpha
      - insomnia
      # - ipartition
      - iterm2
      - keybase
      # - kdiff3
      - ngrok
      # - notational-velocity
      - microsoft-office
      # - musicbrainz-picard
      - onedrive
      - pomello
      - sqlpro-for-sqlite
      # - skype
      - slack
      - spectacle
      - sublime-text
      # - switch
      # - synology-assistant
      - the-unarchiver
      - torbrowser
      # - transmission
      # - viscosity
      - vlc
      - whatsapp
    # fonts
      # - font-arvo # for OAKWEAR & CO.
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      # - { id: 824183456, name: "Affinity Photo" }
      # - { id: 824171161, name: "Affinity Designer" }
      - { id: 979047768, name: "Browserism for Chrome" }
      - { id: 420212497, name: "Byword (2.8)" }
      - { id: 975937182, name: "Fantastical 2 - Calendar and Reminders" }
      # - { id: 424389933, name: "Final Cut Pro" }
      # - { id: 402989379, name: "iStudiez Pro - Homework, Schedule, Grades" }
      - { id: 409201541, name: "Pages" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Mail
        path: "/Applications/Mail.app"
        pos: 3
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 4
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 5
      - name: WhatsApp
        path: "/Applications/WhatsApp.app"
        pos: 6
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 7
      - name: Google Chrome Canary
        path: "/Applications/Google Chrome Canary.app"
        pos: 8
      - name: Firefox
        path: "/Applications/Firefox.app"
        pos: 9
      - name: TorBrowser
        path: "/Applications/TorBrowser.app"
        pos: 10
      - name: Atom
        path: /Applications/Atom.app
        pos: 11
      - name: Byword
        path: /Applications/Byword.app
        pos: 12
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 13
      - name: Pomello
        path: /Applications/Pomello.app
        pos: 14
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 15
