---

- hosts: macbox
  connection: local
  roles:
    - spoof-mac
    - etchosts
    # - oh-my-zsh
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - aliases
    - functions
    - git
    - tmux
    - vim
    - atom
    - sublime-text
    - macdown
    # - ssh #id_rsa key generation
    - privoxy
    - syncthing
    - automator-workflows
    - anaconda
    # - dnscrypt
    # - gpg
    # - mas
    - dockutil
    - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    become_skip: true
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_cask_appdir: /Applications
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-fonts
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - getantibody/homebrew-antibody
    homebrew_installed_packages:
      - antibody
    homebrew_cask_apps:

    sublime_packages:
      - dest: "Solarized"
        repo: "https://github.com/braver/Solarized.git"
        version: "master"
      - dest: "SideBarEnhancements"
        repo: "https://github.com/titoBouzout/SideBarEnhancements"
        version: "st3"
      - dest: "GitGutter"
        repo: "https://github.com/jisaacks/GitGutter.git"
        version: "master"
      - dest: "BracketHighlighter"
        repo: "https://github.com/facelessuser/BracketHighlighter.git"
        version: "master"
      - dest: "ApplySyntax"
        repo: "https://github.com/facelessuser/ApplySyntax.git"
        version: "master"
      - dest: "SublimeAllAutocomplete"
        repo: "https://github.com/alienhard/SublimeAllAutocomplete"
        version: "master"
      - dest: "Ansible"
        repo: "https://github.com/clifford-github/sublime-ansible.git"
        version: "master"
    sublime_text_color_scheme: "Packages/Solarized/Solarized (dark).tmTheme"
    # sublime_text_theme: "Soda Dark 3.sublime-theme"

    atom_packages:
      - busy-signal
      - language-babel
      - language-docker
      - language-gdb
      - language-javascript-jsx
      - language-markdown
      - language-scala
      - linter
      - linter-eslint
      - linter-ui-default
      - intentions
      - markdown-preview-plus
      - markdown-scroll-sync
      - markdown-writer
      - multi-cursor
      - remote-sync

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      - { id: 824183456, name: "Affinity Photo" }
      - { id: 824171161, name: "Affinity Designer" }
      - { id: 979047768, name: "Browserism for Chrome" }
      - { id: 420212497, name: "Byword (2.8)" }
      - { id: 975937182, name: "Fantastical 2 - Calendar and Reminders" }
      - { id: 424389933, name: "Final Cut Pro" }
      - { id: 402989379, name: "iStudiez Pro - Homework, Schedule, Grades" }
      - { id: 409201541, name: "Pages" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 2
      - name: Signal
        path: "/Applications/Signal.app"
        pos: 3
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 4
      - name: Firefox Developer Edition
        path: "/Applications/Firefox Developer Edition.app"
        pos: 5
      - name: Safari
        path: "/Applications/Safari.app"
        pos: 6
      - name: MacDown
        path: /Applications/MacDown.app
        pos: 7
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app
        pos: 8
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 9
      - name: Preview
        path: /Applications/Preview.app
        pos: 10
      - name: iTunes
        path: /Applications/iTunes.app
        pos: 11
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 12

    dockitems_to_remove: