---

- hosts: macbox
  connection: local
  roles:
    - etchosts
  become: yes
  become_method: sudo

  vars:
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true
