---

- hosts: macbox
  connection: local
  roles:
    - dockutil
  become_method: sudo
  vars:
    dockitems_to_persist:
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 1
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 2
      - name: Firefox Developer Edition
        path: "/Applications/Firefox Developer Edition.app"
        pos: 3
      - name: MacDown
        path: /Applications/MacDown.app
        pos: 4
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app
        pos: 5
      - name: IntelliJ IDEA
        path: /Applications/IntelliJ IDEA.app
        pos: 6
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 7
      - name: Preview
        path: /Applications/Preview.app
        pos: 8
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 9

    dockitems_to_remove: