---

- hosts: macbox
  connection: local
  roles:
    - etchosts
    - zsh
    - homebrew
    - dockutil
    - git
    - tmux
    - vim
    - atom
    - ssh
    - privoxy
    # - dnscrypt
    # - gpg
    # - mas
    # - sublime-text
    - macos
    - iterm2
  become: yes
  become_method: sudo

  vars:
    user_name: me
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"

    filevault_auto_evict: true
    cache_libraries: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/cask
      - caskroom/versions
      - caskroom/fonts
    homebrew_installed_packages:
      - dockutil
      # - gnupg2 requires java...
      - htop
      - mas
      - node
      - openssl
      - privoxy
      - tmux
      - yarn
      - zsh-syntax-highlighting
    homebrew_cask_apps:
      - 1password
      - alfred
      - appcleaner
      - atom
      # - autodmg
      # - backblaze
      # - backblaze-downloader
      # - bartender
      # - calibre
      - coda
      - docker
      - dropbox
      - flux
      - google-chrome
      - google-chrome-canary
      - gpgtools-beta
      # - handbrake
      # - handbrakebatch
      # - imagealpha
      # - ipartition
      - iterm2
      # - keybase
      # - kdiff3
      # - nylas-mail
      - microsoft-office
      # - musicbrainz-picard
      # - skype
      - slack
      - spectacle
      # - switch
      # - synology-assistant
      - the-unarchiver
      - torbrowser
      # - transmission
      # - viscosity
      - vlc
    # fonts
      - font-fira-code
      - font-fira-mono-for-powerline
      - font-fontawesome

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      # - { id: 824183456, name: "Affinity Photo" }
      # - { id: 824171161, name: "Affinity Designer" }
      - { id: 979047768, name: "Browserism for Chrome" }
      - { id: 420212497, name: "Byword (2.8)" }
      - { id: 975937182, name: "Fantastical 2 - Calendar and Reminders" }
      # - { id: 424389933, name: "Final Cut Pro" }
      # - { id: 402989379, name: "iStudiez Pro - Homework, Schedule, Grades" }
      - { id: 409201541, name: "Pages" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 3
      - name: Messages
        path: "/Applications/Messages.app"
        pos: 4
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 5
      - name: Google Chrome Canary
        path: "/Applications/Google Chrome Canary.app"
        pos: 6
      - name: TorBrowser
        path: "/Applications/TorBrowser.app"
        pos: 7
      - name: Atom
        path: /Applications/Atom.app
        pos: 8
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 9
      - name: System Preferences
        path: /Applications/System Preferences.app
        pos: 10
