- hosts: macbox
  connection: local
  roles:
    - homebrew
    - atom
  become_method: sudo
  ignore_errors: true
  vars:
    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
    homebrew_installed_packages:
      - node
      - wget
      - yarn
    homebrew_cask_apps:
      - atom
      - docker
