- hosts: macbox
  connection: local
  roles:
    - homebrew
    - bash
    - zsh
    - zsh-antibody
    - zmv
    - fasd
    - fzf
    - adrw-shell
    - git
    - tmux
    - vim
    - ssh
    - nvm
    - npm
    - iterm2
    # - go
    # - travis
    # - oh-my-zsh
    # - mas
  become_method: sudo
  ignore_errors: true
  vars:
    install_homebrew_packages: true
    install_homebrew_fonts: true
